[test]
levels = ["syntax", "install", "execution"]

[test.workflows]
timeout = 300
cpu = ['apply_animation','skeleton_comparison','rigged_manipulator']
gpu = "all"

[test.platforms]
# CPU platforms
linux = false
macos = false
windows = false
windows_portable = true
linux_gpu = false
windows_gpu = true
windows_portable_gpu = false