python = "3.11"  # Required by bpy 4.2

[cuda]
packages = ["torch-scatter", "torch-cluster", "flash-attn", "torch", "torchvision", "cumm", "spconv"]

[pypi-dependencies]
# Blender
bpy = ">=4.2,<4.3"

# Core
numpy = "<2.0"
trimesh = { version = "*", extras = ["easy"] }
psutil = "*"
comfy-aimdo = "*"

# ML libs
transformers = "==4.51.3"
pytorch_lightning = "*"
lightning = "*"
timm = "*"
einops = "*"
addict = "*"
omegaconf = "*"
huggingface_hub = "*"
wandb = "*"
hf_xet = "*"

# Geometry
fast-simplification = "*"
pyrender = "*"
libigl = "*"
pccm = "*"
shapely = "*"

[target.linux-64.pypi-dependencies]
triton = ">=3.0.0"
embreex = "*"

[target.win-64.pypi-dependencies]
triton-windows = "*"
embreex = "*"
comfy-sparse-attn = "*"